---
apiVersion: v1
kind: Secret
metadata:
  name: backup-restore-sidecar-backup-provider-config
type: Opaque
stringData:
  bucketName: my-backup-bucket
  region: us-east-1
  endpoint: <url of s3 endpoint, e.g. https://s3.example.com>
  access-key: <your s3 access-key>
  secret-key: <your s3-secret-key>
